# Generated by Django 4.1.3 on 2022-12-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='TBD', max_length=100),
        ),
    ]
